version: '3.1'

services:

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_DATABASE: 'kinolist'
    ports:
      - "3306:3306"
